apiVersion: v1
kind: ConfigMap
metadata:
  name: chatgpt-config
data:
  OPENAI_API_KEY: {{ .Values.config.openAiApiKey }}
  CODE: {{ .Values.config.code }}
  PROXY_URL: {{ .Values.config.proxyUrl }}
  ENABLE_MCP: {{ .Values.config.enableMcp | quote }}
